import {FileManager} from '../file-manager';

export function setupGit(fileManager: FileManager): void {
  fileManager.registerTextFile(
    '.gitignore',
    ({nonVersionedPaths}) => [
      '# This file is generated by tscmd. Manual changes can be overwritten.',
      ...nonVersionedPaths,
    ],
    {versioned: true}
  );
}
